platform: x64
shallow_clone: true
clone_depth: 10
clone_folder: c:\projects\counterfeiter

stack: go 1.16

environment:
  GOPATH: c:\gopath
  COUNTERFEITER_NO_GENERATE_WARNING: true

before_test:
  - go vet ./...

test_script:
  - go install .
  - copy scripts\counterfeiter.bat c:\gopath\bin
  - set PATH=c:\gopath\bin;c:\go\bin;%PATH%
  - go generate ./...
  - go build -v ./...
  - go test -v -race ./...

build: off
deploy: off
